build: false

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"
    - PYTHON: "C:/Python37-x64"


install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Installing Poetry
  - "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python"
  - "SET PATH=%USERPROFILE%\\.poetry\\bin;%PATH%"

  # Ensure latest pip in Poetry's virtualenv
  - "poetry run python -m pip install -U pip"

  # Install dependencies
  - "poetry install -v"

test_script:
  - "poetry run pytest --cov cleo tests/"
